package com.slgtranslator.app;

import java.io.Closeable;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * File-backed payloads used while rewriting an APK. Entry metadata stays
 * small; generated bytes are never retained in a collection after add().
 */
public final class PendingApkEntryStore implements Closeable {
    private static final int COPY_BUFFER_SIZE = 64 * 1024;

    private final File directory;
    private final List<Entry> entries = new ArrayList<>();
    private boolean closed;

    public PendingApkEntryStore(File directory) throws IOException {
        if (directory == null) {
            throw new IOException("pending entry directory is null");
        }
        this.directory = directory;
        if (directory.exists() && !directory.isDirectory()) {
            throw new IOException("pending entry path is not a directory");
        }
        if (!directory.isDirectory() && !directory.mkdirs()) {
            throw new IOException("cannot create pending entry directory");
        }
    }

    public int add(String apkName, String runtimeName, byte[] payload) throws IOException {
        ensureOpen();
        validateName(apkName, "apkName");
        validateName(runtimeName, "runtimeName");
        File target = File.createTempFile("payload-", ".bin", directory);
        try {
            writePayload(target, payload == null ? new byte[0] : payload);
            entries.add(new Entry(apkName, runtimeName, target, target.length()));
            return entries.size() - 1;
        } catch (Throwable error) {
            target.delete();
            if (error instanceof IOException) {
                throw (IOException) error;
            }
            throw new IOException("failed to spool APK entry", error);
        }
    }

    public InputStream openPayload(int index) throws IOException {
        ensureOpen();
        return new FileInputStream(entryAt(index).payload);
    }

    public void replace(int index, byte[] payload) throws IOException {
        ensureOpen();
        Entry entry = entryAt(index);
        File replacement = File.createTempFile("payload-replace-", ".bin", directory);
        try {
            byte[] nextPayload = payload == null ? new byte[0] : payload;
            long nextLength = nextPayload.length;
            writePayload(replacement, nextPayload);
            if (!entry.payload.delete()) {
                throw new IOException("cannot remove previous APK entry payload");
            }
            if (!replacement.renameTo(entry.payload)) {
                throw new IOException("cannot install replacement APK entry payload");
            }
            entry.length = nextLength;
        } catch (Throwable error) {
            replacement.delete();
            if (error instanceof IOException) {
                throw (IOException) error;
            }
            throw new IOException("failed to replace spooled APK entry", error);
        }
    }

    public String apkName(int index) throws IOException {
        ensureOpen();
        return entryAt(index).apkName;
    }

    public String runtimeName(int index) throws IOException {
        ensureOpen();
        return entryAt(index).runtimeName;
    }

    public int size() {
        return entries.size();
    }

    /** Payload bytes are file-backed immediately after add/replace. */
    public long inMemoryPayloadBytes() {
        return 0L;
    }

    /** Returns the total payload bytes currently reserved on disk. */
    public long totalPayloadBytes() {
        long total = 0L;
        for (Entry entry : entries) {
            if (Long.MAX_VALUE - total < entry.length) {
                return Long.MAX_VALUE;
            }
            total += entry.length;
        }
        return total;
    }

    /** Package-private so the compiler can account for the payload file store. */
    File storageDirectory() {
        return directory;
    }

    @Override
    public void close() {
        if (closed) {
            return;
        }
        closed = true;
        for (Entry entry : entries) {
            if (entry.payload.exists()) {
                entry.payload.delete();
            }
        }
        entries.clear();
        if (directory.exists()) {
            directory.delete();
        }
    }

    private Entry entryAt(int index) throws IOException {
        if (index < 0 || index >= entries.size()) {
            throw new IOException("pending entry index out of range: " + index);
        }
        return entries.get(index);
    }

    private void ensureOpen() throws IOException {
        if (closed) {
            throw new IOException("pending entry store is closed");
        }
    }

    private static void validateName(String value, String field) throws IOException {
        if (value == null || value.isEmpty() || value.indexOf('\u0000') >= 0) {
            throw new IOException(field + " is invalid");
        }
    }

    private static void writePayload(File target, byte[] payload) throws IOException {
        try (FileOutputStream output = new FileOutputStream(target)) {
            int offset = 0;
            while (offset < payload.length) {
                int count = Math.min(COPY_BUFFER_SIZE, payload.length - offset);
                output.write(payload, offset, count);
                offset += count;
            }
            output.flush();
            output.getFD().sync();
        }
    }

    private static final class Entry {
        final String apkName;
        final String runtimeName;
        final File payload;
        long length;

        Entry(String apkName, String runtimeName, File payload, long length) {
            this.apkName = apkName;
            this.runtimeName = runtimeName;
            this.payload = payload;
            this.length = length;
        }
    }
}
