import type { ApkEntry } from "./filemanager"
import type { TextItem } from "./types"

const RENPY_LANGUAGE_DIRS: Record<string, string> = {
  zh: "schinese",
  en: "english",
  ja: "japanese",
  ko: "korean",
  fr: "french",
  de: "german",
  ru: "russian",
  pt: "portuguese",
  th: "thai",
  vi: "vietnamese",
}

export function isRenPyEntry(entry: ApkEntry): boolean {
  return entry.fileType === "rpyc" || entry.fileType === "rpy"
}

export function buildRenPyTranslationFile(
  entry: ApkEntry,
  texts: TextItem[],
  translations: Map<string, string>,
  targetLang: string,
): { outputPath: string; content: string; count: number } {
  const languageName = getRenPyLanguageName(targetLang)
  const translationPairs = collectTranslationPairs(texts, translations)
  const outputPath = buildRenPyTranslationPath(entry.name, languageName)

  return {
    outputPath,
    content: renderStringTranslationFile(entry.name, languageName, translationPairs),
    count: translationPairs.length,
  }
}

export function getRenPyLanguageName(targetLang: string): string {
  return RENPY_LANGUAGE_DIRS[targetLang] || targetLang
}

function collectTranslationPairs(
  texts: TextItem[],
  translations: Map<string, string>,
): Array<{ oldText: string; newText: string }> {
  const pairs = new Map<string, string>()

  for (const item of texts) {
    const translatedText = translations.get(item.keyPath) || translations.get(item.text)
    if (!translatedText?.trim()) continue

    const oldText = item.text.trim()
    const newText = translatedText.trim()
    if (!oldText || !newText || pairs.has(oldText)) continue

    pairs.set(oldText, newText)
  }

  return Array.from(pairs, ([oldText, newText]) => ({ oldText, newText }))
}

function buildRenPyTranslationPath(entryName: string, languageName: string): string {
  const normalizedName = entryName.replace(/\\/g, "/")
  const withoutExtension = normalizedName.replace(/\.[^/.]+$/, "")
  const parts = withoutExtension.split("/")
  const translationIndex = parts.findIndex((part) => part === "tl" || part === "x-tl")

  if (translationIndex >= 0 && parts[translationIndex + 1]) {
    parts[translationIndex + 1] = withExistingPrefix(parts[translationIndex + 1], languageName)
    return `${parts.join("/")}.rpy`
  }

  const gameIndex = parts.findIndex((part) => part === "game" || part === "x-game")
  if (gameIndex >= 0) {
    const root = parts.slice(0, gameIndex + 1)
    const rest = parts.slice(gameIndex + 1)
    const usesPrefixedNames = parts[gameIndex].startsWith("x-")
    const tlDir = usesPrefixedNames ? "x-tl" : "tl"
    const langDir = usesPrefixedNames ? `x-${languageName}` : languageName
    return [...root, tlDir, langDir, ...rest].join("/") + ".rpy"
  }

  return `tl/${languageName}/${parts.at(-1) || "strings"}.rpy`
}

function withExistingPrefix(existingLanguageDir: string, languageName: string): string {
  return existingLanguageDir.startsWith("x-") ? `x-${languageName}` : languageName
}

function renderStringTranslationFile(
  sourcePath: string,
  languageName: string,
  pairs: Array<{ oldText: string; newText: string }>,
): string {
  const lines = [
    "# Generated by SLG Translator Android.",
    `# Source: ${sourcePath}`,
    `translate ${languageName} strings:`,
    "",
  ]

  for (const pair of pairs) {
    lines.push(`    old ${toRenPyStringLiteral(pair.oldText)}`)
    lines.push(`    new ${toRenPyStringLiteral(pair.newText)}`)
    lines.push("")
  }

  return lines.join("\n")
}

function toRenPyStringLiteral(value: string): string {
  return JSON.stringify(value)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029")
}
